controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

#user_test:
#    path: /user/test
#    controller: App\Controller\UserController
